<?php
    /** @var $block \Magento\Catalog\Block\Product\View */

    /** @var \ClassyLlama\Credova\ViewModel\Qualification $viewModel */
    $viewModel = $block->getViewModel();
?>

<?php
    // NB: the plugin JS fails with `document.body is null` errors if included in the head.
    // As such, it's being included at the end of the body.
?>
<script src="https://plugin.credova.com/plugin.min.js"></script>
<script>
    CRDV.plugin.config({
        environment: <?= $block->escapeJs($viewModel->getEnvironmentConstant()) ?>,
        store: "<?= $block->escapeJs($viewModel->getConfigHelper()->getCredovaStoreCode()) ?>"
    });
</script>
<script type="text/x-magento-init">
{
    "#credova-qualification-button": {
        "credovaQualificationPopup": {
            "minimumAmount": "<?= $block->escapeJs($viewModel->getConfigHelper()->getCredovaMinimumAmount()) ?>"
        }
    }
}
</script>
